dist: bionic
language: c
compiler: gcc
addons:
  apt:
    packages:
      - intltool
      - libgtk2.0-dev
script:
    - libtoolize --copy --force
    - ./autogen.sh
    - make
    - make dist
deploy:
  provider: releases
  api_key: $APIKEY
  file: gcolpicker*.tar.gz
  skip_cleanup: true
  on:
    tags: true
