dist: bionic
language: c
compiler: gcc
addons:
  apt:
    packages:
      - intltool
      - libgtk2.0-dev
script:
    - libtoolize --copy --force
    - ./autogen.sh
    - make
    - make dist
deploy:
  provider: releases
  api_key: "c8a955ee8ee446011bbd7d6a2ee2e1ace5ea30ce"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
