/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gcolor2 (void);
GtkWidget* create_save_dialog (void);
GtkWidget* create_popup_menu (void);
GtkWidget* create_about_dialog (void);
GtkWidget* create_delete_dialog (void);
